### ISSUE TITLE
链接无法访问

### ISSUE THREAD

**Issue by cloudinbanana** [datawhalechina/Datawhale-Navigation#1]
**links can not open**

**Comment by nicexiaocao** [comment]
链接打不开

**Comment by youngfish42** [comment]
超链接是空的，项目无法跳转

**Comment by Sm1les** [comment]
@cloudinbanana @firewang @nicexiaocao @youngfish42 同学们非常抱歉，这个repo是我们的一个计划大纲，但是很多内容尚未开发完全，所以链接目前都是空的，现在我已经将其暂时撤下了，等我们将各项内容都开发好了以后再给大家呈上来，感谢你们对Datawhale的关注，敬请期待我们后续的工作 :)
